version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
  prod:
    build:
      context: .
      dockerfile: prod.Dockerfile
    ports:
      - '8080:8080'
